#pragma once

// GPIO pin map for STM32G4 (RM0440 rev 7).
// Generated from the datasheet alternate-function tables, DO NOT EDIT.

#include <stdint.h>

typedef uint64_t pinconf_t; // low 32: GPIO_Pin (port+mask), high 32: GPIO_Conf

enum GPIO_Pin {
	Pin_0  = 0x0001,
	Pin_1  = 0x0002,
	Pin_2  = 0x0004,
	Pin_3  = 0x0008,
	Pin_4  = 0x0010,
	Pin_5  = 0x0020,
	Pin_6  = 0x0040,
	Pin_7  = 0x0080,
	Pin_8  = 0x0100,
	Pin_9  = 0x0200,
	Pin_10 = 0x0400,
	Pin_11 = 0x0800,
	Pin_12 = 0x1000,
	Pin_13 = 0x2000,
	Pin_14 = 0x4000,
	Pin_15 = 0x8000,
	Pin_All = 0xFFFF,

	GPIO_A = 0x01000000,
	GPIO_B = 0x02010000,
	GPIO_C = 0x04020000,
	GPIO_D = 0x08030000,
	GPIO_E = 0x10040000,
	GPIO_F = 0x20050000,
	GPIO_G = 0x40060000,

	PA0  = GPIO_A | Pin_0,	PA1  = GPIO_A | Pin_1,	PA2  = GPIO_A | Pin_2,	PA3  = GPIO_A | Pin_3,	PA4  = GPIO_A | Pin_4,	PA5  = GPIO_A | Pin_5,	PA6  = GPIO_A | Pin_6,	PA7  = GPIO_A | Pin_7,	PA8  = GPIO_A | Pin_8,	PA9  = GPIO_A | Pin_9,	PA10 = GPIO_A | Pin_10,	PA11 = GPIO_A | Pin_11,	PA12 = GPIO_A | Pin_12,	PA13 = GPIO_A | Pin_13,	PA14 = GPIO_A | Pin_14,	PA15 = GPIO_A | Pin_15,
	PAAll = GPIO_A | Pin_All,
	PAMost = GPIO_A | (Pin_All & ~(Pin_13 | Pin_14)), // port A minus SWDIO(PA13)/SWCLK(PA14)
	PB0  = GPIO_B | Pin_0,	PB1  = GPIO_B | Pin_1,	PB2  = GPIO_B | Pin_2,	PB3  = GPIO_B | Pin_3,	PB4  = GPIO_B | Pin_4,	PB5  = GPIO_B | Pin_5,	PB6  = GPIO_B | Pin_6,	PB7  = GPIO_B | Pin_7,	PB8  = GPIO_B | Pin_8,	PB9  = GPIO_B | Pin_9,	PB10 = GPIO_B | Pin_10,	PB11 = GPIO_B | Pin_11,	PB12 = GPIO_B | Pin_12,	PB13 = GPIO_B | Pin_13,	PB14 = GPIO_B | Pin_14,	PB15 = GPIO_B | Pin_15,
	PBAll = GPIO_B | Pin_All,
	PC0  = GPIO_C | Pin_0,	PC1  = GPIO_C | Pin_1,	PC2  = GPIO_C | Pin_2,	PC3  = GPIO_C | Pin_3,	PC4  = GPIO_C | Pin_4,	PC5  = GPIO_C | Pin_5,	PC6  = GPIO_C | Pin_6,	PC7  = GPIO_C | Pin_7,	PC8  = GPIO_C | Pin_8,	PC9  = GPIO_C | Pin_9,	PC10 = GPIO_C | Pin_10,	PC11 = GPIO_C | Pin_11,	PC12 = GPIO_C | Pin_12,	PC13 = GPIO_C | Pin_13,	PC14 = GPIO_C | Pin_14,	PC15 = GPIO_C | Pin_15,
	PCAll = GPIO_C | Pin_All,
	PD0  = GPIO_D | Pin_0,	PD1  = GPIO_D | Pin_1,	PD2  = GPIO_D | Pin_2,	PD3  = GPIO_D | Pin_3,	PD4  = GPIO_D | Pin_4,	PD5  = GPIO_D | Pin_5,	PD6  = GPIO_D | Pin_6,	PD7  = GPIO_D | Pin_7,	PD8  = GPIO_D | Pin_8,	PD9  = GPIO_D | Pin_9,	PD10 = GPIO_D | Pin_10,	PD11 = GPIO_D | Pin_11,	PD12 = GPIO_D | Pin_12,	PD13 = GPIO_D | Pin_13,	PD14 = GPIO_D | Pin_14,	PD15 = GPIO_D | Pin_15,
	PDAll = GPIO_D | Pin_All,
	PE0  = GPIO_E | Pin_0,	PE1  = GPIO_E | Pin_1,	PE2  = GPIO_E | Pin_2,	PE3  = GPIO_E | Pin_3,	PE4  = GPIO_E | Pin_4,	PE5  = GPIO_E | Pin_5,	PE6  = GPIO_E | Pin_6,	PE7  = GPIO_E | Pin_7,	PE8  = GPIO_E | Pin_8,	PE9  = GPIO_E | Pin_9,	PE10 = GPIO_E | Pin_10,	PE11 = GPIO_E | Pin_11,	PE12 = GPIO_E | Pin_12,	PE13 = GPIO_E | Pin_13,	PE14 = GPIO_E | Pin_14,	PE15 = GPIO_E | Pin_15,
	PEAll = GPIO_E | Pin_All,
	PF0  = GPIO_F | Pin_0,	PF1  = GPIO_F | Pin_1,	PF2  = GPIO_F | Pin_2,	PF3  = GPIO_F | Pin_3,	PF4  = GPIO_F | Pin_4,	PF5  = GPIO_F | Pin_5,	PF6  = GPIO_F | Pin_6,	PF7  = GPIO_F | Pin_7,	PF8  = GPIO_F | Pin_8,	PF9  = GPIO_F | Pin_9,	PF10 = GPIO_F | Pin_10,	PF11 = GPIO_F | Pin_11,	PF12 = GPIO_F | Pin_12,	PF13 = GPIO_F | Pin_13,	PF14 = GPIO_F | Pin_14,	PF15 = GPIO_F | Pin_15,
	PFAll = GPIO_F | Pin_All,
	PG0  = GPIO_G | Pin_0,	PG1  = GPIO_G | Pin_1,	PG2  = GPIO_G | Pin_2,	PG3  = GPIO_G | Pin_3,	PG4  = GPIO_G | Pin_4,	PG5  = GPIO_G | Pin_5,	PG6  = GPIO_G | Pin_6,	PG7  = GPIO_G | Pin_7,	PG8  = GPIO_G | Pin_8,	PG9  = GPIO_G | Pin_9,	PG10 = GPIO_G | Pin_10,	PG11 = GPIO_G | Pin_11,	PG12 = GPIO_G | Pin_12,	PG13 = GPIO_G | Pin_13,	PG14 = GPIO_G | Pin_14,	PG15 = GPIO_G | Pin_15,
	PGAll = GPIO_G | Pin_All,
};

enum GPIO_Conf {
	GPIO_INPUT  = 0x0000,
	GPIO_OUTPUT = 0x1000,
	GPIO_AFOUT  = 0x2000,
	GPIO_ANALOG = 0x3000,

	GPIO_OPENDRAIN = 0x0080, // OTYPE, output/af only (0 = push-pull)

	GPIO_PULLUP   = 0x0010, // PUPD
	GPIO_PULLDOWN = 0x0020,

	GPIO_LOW    = 0x0000, // OSPEED, output/af only
	GPIO_MEDIUM = 0x0001,
	GPIO_FAST   = 0x0002,
	GPIO_HIGH   = 0x0003,
};

enum GPIO_Flag {
	PIN_INPUT     = (pinconf_t)GPIO_INPUT << 32,
	PIN_OUTPUT    = (pinconf_t)GPIO_OUTPUT << 32,
	PIN_ANALOG    = (pinconf_t)GPIO_ANALOG << 32,
	PIN_OPENDRAIN = (pinconf_t)GPIO_OPENDRAIN << 32,
	PIN_PULLUP    = (pinconf_t)GPIO_PULLUP << 32,
	PIN_PULLDOWN  = (pinconf_t)GPIO_PULLDOWN << 32,
	PIN_LOW       = (pinconf_t)GPIO_LOW << 32,
	PIN_MEDIUM    = (pinconf_t)GPIO_MEDIUM << 32,
	PIN_FAST      = (pinconf_t)GPIO_FAST << 32,
	PIN_HIGH      = (pinconf_t)GPIO_HIGH << 32,
};

// Datasheet (pin, function) -> pin with the correct AF baked in. A pair
// that does not exist here is not a legal mux: using it is a compile error.
enum GPIO_Mux {
	PA0_TIM2_CH1             = (pinconf_t)PA0   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA0_TIM5_CH1             = (pinconf_t)PA0   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32), // Cat3,4 only
	PA0_USART2_CTS           = (pinconf_t)PA0   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA0_COMP1_OUT            = (pinconf_t)PA0   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PA0_TIM8_BKIN            = (pinconf_t)PA0   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PA0_TIM8_ETR             = (pinconf_t)PA0   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PA0_TIM2_ETR             = (pinconf_t)PA0   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PA0_EVENTOUT             = (pinconf_t)PA0   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA1_RTC_REFIN            = (pinconf_t)PA1   | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PA1_TIM2_CH2             = (pinconf_t)PA1   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA1_TIM5_CH2             = (pinconf_t)PA1   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32), // Cat3,4 only
	PA1_USART2_RTS_DE        = (pinconf_t)PA1   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA1_TIM15_CH1N           = (pinconf_t)PA1   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PA1_EVENTOUT             = (pinconf_t)PA1   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA10_TIM17_BKIN          = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA10_I2C3_SCL            = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32), // G473/G483 only
	PA10_USB_CRS_SYNC        = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PA10_I2C2_SMBA           = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PA10_SPI2_MISO           = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA10_TIM1_CH3            = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA10_USART1_RX           = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA10_COMP6_OUT           = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32), // Cat3,4 only
	PA10_FDCAN1_TX           = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32), // G473/G483 only
	PA10_TIM2_CH4            = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PA10_TIM8_BKIN           = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32),
	PA10_SAI1_D1             = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PA10_HRTIM1_CHB1         = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PA10_SAI1_SD_A           = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PA10_EVENTOUT            = (pinconf_t)PA10  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA11_SPI2_MOSI           = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA11_TIM1_CH1N           = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA11_USART1_CTS          = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA11_COMP1_OUT           = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PA11_FDCAN1_RX           = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PA11_TIM4_CH1            = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PA11_TIM1_CH4            = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32),
	PA11_TIM1_BKIN2          = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PA11_HRTIM1_CHB2         = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PA11_EVENTOUT            = (pinconf_t)PA11  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA12_TIM16_CH1           = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA12_I2SCKIN             = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA12_TIM1_CH2N           = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA12_USART1_RTS_DE       = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA12_COMP2_OUT           = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PA12_FDCAN1_TX           = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PA12_TIM4_CH2            = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PA12_TIM1_ETR            = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32),
	PA12_HRTIM1_FLT1         = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PA12_EVENTOUT            = (pinconf_t)PA12  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA13_SWDIO_JTMS          = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PA13_TIM16_CH1N          = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA13_I2C4_SCL            = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat4 only
	PA13_I2C1_SCL            = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PA13_IR_OUT              = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA13_USART3_CTS          = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA13_TIM4_CH3            = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PA13_SAI1_SD_B           = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32),
	PA13_EVENTOUT            = (pinconf_t)PA13  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA14_SWCLK_JTCK          = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PA14_LPTIM1_OUT          = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA14_I2C4_SMBA           = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat3,4 only
	PA14_I2C1_SDA            = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PA14_TIM8_CH2            = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA14_TIM1_BKIN           = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA14_USART2_TX           = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA14_FDCAN3_TX           = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32), // G473/G483 only
	PA14_SAI1_FS_B           = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32),
	PA14_EVENTOUT            = (pinconf_t)PA14  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA15_JTDI                = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PA15_TIM2_CH1            = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA15_TIM8_CH1            = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PA15_I2C1_SCL            = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PA15_SPI1_NSS            = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA15_SPI3_NSS            = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA15_USART2_RX           = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA15_UART4_RTS_DE        = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PA15_TIM1_BKIN           = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PA15_FDCAN3_TX           = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32), // Cat3,4 only
	PA15_HRTIM1_FLT2         = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PA15_TIM2_ETR            = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PA15_EVENTOUT            = (pinconf_t)PA15  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA2_TIM2_CH3             = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA2_TIM5_CH3             = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32), // Cat3,4 only
	PA2_USART2_TX            = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA2_COMP2_OUT            = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PA2_TIM15_CH1            = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PA2_QUADSPI1_BK1_NCS     = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PA2_LPUART1_TX           = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PA2_UCPD1_FRSTX          = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PA2_EVENTOUT             = (pinconf_t)PA2   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA3_TIM2_CH4             = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA3_TIM5_CH4             = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32), // Cat3,4 only
	PA3_SAI1_CK1             = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PA3_USART2_RX            = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA3_TIM15_CH2            = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PA3_QUADSPI1_CLK         = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PA3_LPUART1_RX           = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PA3_SAI1_MCLK_A          = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32),
	PA3_EVENTOUT             = (pinconf_t)PA3   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA4_TIM3_CH2             = (pinconf_t)PA4   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PA4_SPI1_NSS             = (pinconf_t)PA4   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA4_SPI3_NSS             = (pinconf_t)PA4   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA4_USART2_CK            = (pinconf_t)PA4   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA4_SAI1_FS_B            = (pinconf_t)PA4   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32),
	PA4_EVENTOUT             = (pinconf_t)PA4   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA5_TIM2_CH1             = (pinconf_t)PA5   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA5_TIM2_ETR             = (pinconf_t)PA5   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PA5_SPI1_SCK             = (pinconf_t)PA5   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA5_UCPD1_FRSTX          = (pinconf_t)PA5   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PA5_EVENTOUT             = (pinconf_t)PA5   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA6_TIM16_CH1            = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA6_TIM3_CH1             = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PA6_TIM8_BKIN            = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PA6_SPI1_MISO            = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA6_TIM1_BKIN            = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA6_COMP1_OUT            = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PA6_QUADSPI1_BK1_IO3     = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PA6_LPUART1_CTS          = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PA6_EVENTOUT             = (pinconf_t)PA6   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA7_TIM17_CH1            = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PA7_TIM3_CH2             = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PA7_TIM8_CH1N            = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PA7_SPI1_MOSI            = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA7_TIM1_CH1N            = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA7_COMP2_OUT            = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PA7_QUADSPI1_BK1_IO2     = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PA7_UCPD1_FRSTX          = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PA7_EVENTOUT             = (pinconf_t)PA7   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA8_MCO                  = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PA8_I2C3_SCL             = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PA8_I2C2_SDA             = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PA8_I2S2_MCK             = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA8_TIM1_CH1             = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA8_USART1_CK            = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA8_COMP7_OUT            = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32), // Cat3,4 only
	PA8_TIM4_ETR             = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PA8_FDCAN3_RX            = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32), // Cat3,4 only
	PA8_SAI1_CK2             = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PA8_HRTIM1_CHA1          = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PA8_SAI1_SCK_A           = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PA8_EVENTOUT             = (pinconf_t)PA8   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PA9_I2C3_SMBA            = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PA9_I2C2_SCL             = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PA9_I2S3_MCK             = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PA9_TIM1_CH2             = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PA9_USART1_TX            = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PA9_COMP5_OUT            = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32), // Cat3,4 only
	PA9_TIM15_BKIN           = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PA9_TIM2_CH3             = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PA9_FDCAN1_RX            = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32), // G473/G483 only
	PA9_HRTIM1_CHA2          = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PA9_SAI1_FS_A            = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PA9_EVENTOUT             = (pinconf_t)PA9   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB0_TIM3_CH3             = (pinconf_t)PB0   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB0_TIM8_CH2N            = (pinconf_t)PB0   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB0_TIM1_CH2N            = (pinconf_t)PB0   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB0_QUADSPI1_BK1_IO1     = (pinconf_t)PB0   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PB0_HRTIM1_FLT5          = (pinconf_t)PB0   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB0_UCPD1_FRSTX          = (pinconf_t)PB0   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PB0_EVENTOUT             = (pinconf_t)PB0   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB1_TIM3_CH4             = (pinconf_t)PB1   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB1_TIM8_CH3N            = (pinconf_t)PB1   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB1_TIM1_CH3N            = (pinconf_t)PB1   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB1_COMP4_OUT            = (pinconf_t)PB1   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB1_QUADSPI1_BK1_IO0     = (pinconf_t)PB1   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PB1_LPUART1_RTS_DE       = (pinconf_t)PB1   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PB1_HRTIM1_SCOUT         = (pinconf_t)PB1   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB1_EVENTOUT             = (pinconf_t)PB1   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB10_TIM2_CH3            = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB10_USART3_TX           = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB10_LPUART1_RX          = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB10_QUADSPI1_CLK        = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PB10_FDCAN3_TX           = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32), // G473/G483 only
	PB10_TIM1_BKIN           = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PB10_HRTIM1_FLT3         = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB10_SAI1_SCK_A          = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PB10_EVENTOUT            = (pinconf_t)PB10  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB11_TIM2_CH4            = (pinconf_t)PB11  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB11_USART3_RX           = (pinconf_t)PB11  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB11_LPUART1_TX          = (pinconf_t)PB11  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB11_QUADSPI1_BK1_NCS    = (pinconf_t)PB11  | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PB11_FDCAN3_RX           = (pinconf_t)PB11  | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32), // G473/G483 only
	PB11_HRTIM1_FLT4         = (pinconf_t)PB11  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB11_EVENTOUT            = (pinconf_t)PB11  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB12_TIM5_ETR            = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32), // Cat3,4 only
	PB12_I2C2_SMBA           = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB12_SPI2_NSS            = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB12_TIM1_BKIN           = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB12_USART3_CK           = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB12_LPUART1_RTS_DE      = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB12_FDCAN2_RX           = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32), // Cat3,4 only
	PB12_HRTIM1_CHC1         = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB12_EVENTOUT            = (pinconf_t)PB12  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB13_SPI2_SCK            = (pinconf_t)PB13  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB13_TIM1_CH1N           = (pinconf_t)PB13  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB13_USART3_CTS          = (pinconf_t)PB13  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB13_LPUART1_CTS         = (pinconf_t)PB13  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB13_FDCAN2_TX           = (pinconf_t)PB13  | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32), // Cat3,4 only
	PB13_HRTIM1_CHC2         = (pinconf_t)PB13  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB13_EVENTOUT            = (pinconf_t)PB13  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB14_TIM15_CH1           = (pinconf_t)PB14  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB14_SPI2_MISO           = (pinconf_t)PB14  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB14_TIM1_CH2N           = (pinconf_t)PB14  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB14_USART3_RTS_DE       = (pinconf_t)PB14  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB14_COMP4_OUT           = (pinconf_t)PB14  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB14_HRTIM1_CHD1         = (pinconf_t)PB14  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB14_EVENTOUT            = (pinconf_t)PB14  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB15_RTC_REFIN           = (pinconf_t)PB15  | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PB15_TIM15_CH2           = (pinconf_t)PB15  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB15_TIM15_CH1N          = (pinconf_t)PB15  | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB15_COMP3_OUT           = (pinconf_t)PB15  | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PB15_TIM1_CH3N           = (pinconf_t)PB15  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB15_SPI2_MOSI           = (pinconf_t)PB15  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB15_HRTIM1_CHD2         = (pinconf_t)PB15  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB15_EVENTOUT            = (pinconf_t)PB15  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB2_RTC_OUT2             = (pinconf_t)PB2   | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PB2_LPTIM1_OUT           = (pinconf_t)PB2   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB2_TIM5_CH1             = (pinconf_t)PB2   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32), // Cat3,4 only
	PB2_TIM20_CH1            = (pinconf_t)PB2   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat3,4 only
	PB2_I2C3_SMBA            = (pinconf_t)PB2   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB2_QUADSPI1_BK2_IO1     = (pinconf_t)PB2   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PB2_HRTIM1_SCIN          = (pinconf_t)PB2   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB2_EVENTOUT             = (pinconf_t)PB2   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB3_JTDO_TRACESWO        = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PB3_TIM2_CH2             = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB3_TIM4_ETR             = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB3_USB_CRS_SYNC         = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PB3_TIM8_CH1N            = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB3_SPI1_SCK             = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB3_SPI3_SCK             = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB3_USART2_TX            = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB3_TIM3_ETR             = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PB3_FDCAN3_RX            = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32), // Cat3,4 only
	PB3_HRTIM1_SCOUT         = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32), // Cat4 only
	PB3_HRTIM1_EEV9          = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB3_SAI1_SCK_B           = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PB3_EVENTOUT             = (pinconf_t)PB3   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB4_JTRST                = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | ( 0 << 8)) << 32),
	PB4_TIM16_CH1            = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB4_TIM3_CH1             = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB4_TIM8_CH2N            = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB4_SPI1_MISO            = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB4_SPI3_MISO            = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB4_USART2_RX            = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB4_UART5_RTS_DE         = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32), // Cat3,4 only
	PB4_TIM17_BKIN           = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PB4_FDCAN3_TX            = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32), // Cat3,4 only
	PB4_HRTIM1_EEV7          = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB4_SAI1_MCLK_B          = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PB4_EVENTOUT             = (pinconf_t)PB4   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB5_TIM16_BKIN           = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB5_TIM3_CH2             = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB5_TIM8_CH3N            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PB5_I2C1_SMBA            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB5_SPI1_MOSI            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB5_SPI3_MOSI            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB5_USART2_CK            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB5_I2C3_SDA             = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB5_FDCAN2_RX            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32), // Cat3,4 only
	PB5_TIM17_CH1            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PB5_LPTIM1_IN1           = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32),
	PB5_SAI1_SD_B            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PB5_HRTIM1_EEV6          = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB5_UART5_CTS            = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32), // Cat3,4 only
	PB5_EVENTOUT             = (pinconf_t)PB5   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB6_TIM16_CH1N           = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB6_TIM4_CH1             = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB6_TIM8_CH1             = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB6_TIM8_ETR             = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB6_USART1_TX            = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB6_COMP4_OUT            = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB6_FDCAN2_TX            = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32), // Cat3,4 only
	PB6_TIM8_BKIN2           = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PB6_LPTIM1_ETR           = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32),
	PB6_HRTIM1_SCIN          = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32), // Cat4 only
	PB6_HRTIM1_EEV4          = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB6_SAI1_FS_B            = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PB6_EVENTOUT             = (pinconf_t)PB6   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB7_TIM17_CH1N           = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB7_TIM4_CH2             = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB7_I2C4_SDA             = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat3,4 only
	PB7_I2C1_SDA             = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB7_TIM8_BKIN            = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PB7_USART1_RX            = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB7_COMP3_OUT            = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB7_FDCAN2_TX            = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32), // G473/G483 only
	PB7_TIM3_CH4             = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PB7_LPTIM1_IN2           = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | (11 << 8)) << 32),
	PB7_FMC_NL               = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32), // Cat3,4 only
	PB7_HRTIM1_EEV3          = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB7_UART4_CTS            = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PB7_EVENTOUT             = (pinconf_t)PB7   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB8_TIM16_CH1            = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB8_TIM4_CH3             = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB8_SAI1_CK1             = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PB8_I2C1_SCL             = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB8_USART3_RX            = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB8_COMP1_OUT            = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB8_FDCAN1_RX            = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PB8_TIM8_CH2             = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PB8_TIM1_BKIN            = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PB8_HRTIM1_EEV8          = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB8_SAI1_MCLK_A          = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PB8_EVENTOUT             = (pinconf_t)PB8   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PB9_TIM17_CH1            = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PB9_TIM4_CH4             = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PB9_SAI1_D2              = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PB9_I2C1_SDA             = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PB9_IR_OUT               = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PB9_USART3_TX            = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PB9_COMP2_OUT            = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PB9_FDCAN1_TX            = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | ( 9 << 8)) << 32),
	PB9_TIM8_CH3             = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32),
	PB9_TIM1_CH3N            = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | (12 << 8)) << 32),
	PB9_HRTIM1_EEV5          = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PB9_SAI1_FS_A            = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PB9_EVENTOUT             = (pinconf_t)PB9   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC0_LPTIM1_IN1           = (pinconf_t)PC0   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PC0_TIM1_CH1             = (pinconf_t)PC0   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC0_LPUART1_RX           = (pinconf_t)PC0   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PC0_EVENTOUT             = (pinconf_t)PC0   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC1_LPTIM1_OUT           = (pinconf_t)PC1   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PC1_TIM1_CH2             = (pinconf_t)PC1   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC1_LPUART1_TX           = (pinconf_t)PC1   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PC1_QUADSPI1_BK2_IO0     = (pinconf_t)PC1   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PC1_SAI1_SD_A            = (pinconf_t)PC1   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32),
	PC1_EVENTOUT             = (pinconf_t)PC1   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC10_TIM8_CH1N           = (pinconf_t)PC10  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC10_UART4_TX            = (pinconf_t)PC10  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PC10_SPI3_SCK            = (pinconf_t)PC10  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC10_USART3_TX           = (pinconf_t)PC10  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PC10_HRTIM1_FLT6         = (pinconf_t)PC10  | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PC10_EVENTOUT            = (pinconf_t)PC10  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC11_HRTIM1_EEV2         = (pinconf_t)PC11  | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat4 only
	PC11_TIM8_CH2N           = (pinconf_t)PC11  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC11_UART4_RX            = (pinconf_t)PC11  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PC11_SPI3_MISO           = (pinconf_t)PC11  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC11_USART3_RX           = (pinconf_t)PC11  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PC11_I2C3_SDA            = (pinconf_t)PC11  | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PC11_EVENTOUT            = (pinconf_t)PC11  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC12_TIM5_CH2            = (pinconf_t)PC12  | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32), // Cat3,4 only
	PC12_HRTIM1_EEV1         = (pinconf_t)PC12  | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat4 only
	PC12_TIM8_CH3N           = (pinconf_t)PC12  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC12_UART5_TX            = (pinconf_t)PC12  | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32), // Cat3,4 only
	PC12_SPI3_MOSI           = (pinconf_t)PC12  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC12_USART3_CK           = (pinconf_t)PC12  | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PC12_UCPD1_FRSTX         = (pinconf_t)PC12  | ((pinconf_t)(GPIO_AFOUT | (14 << 8)) << 32),
	PC12_EVENTOUT            = (pinconf_t)PC12  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC13_TIM1_BKIN           = (pinconf_t)PC13  | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC13_TIM1_CH1N           = (pinconf_t)PC13  | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC13_TIM8_CH4N           = (pinconf_t)PC13  | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC13_EVENTOUT            = (pinconf_t)PC13  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC14_EVENTOUT            = (pinconf_t)PC14  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC15_EVENTOUT            = (pinconf_t)PC15  | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC2_LPTIM1_IN2           = (pinconf_t)PC2   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PC2_TIM1_CH3             = (pinconf_t)PC2   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC2_COMP3_OUT            = (pinconf_t)PC2   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PC2_TIM20_CH2            = (pinconf_t)PC2   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32), // Cat3,4 only
	PC2_QUADSPI1_BK2_IO1     = (pinconf_t)PC2   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PC2_EVENTOUT             = (pinconf_t)PC2   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC3_LPTIM1_ETR           = (pinconf_t)PC3   | ((pinconf_t)(GPIO_AFOUT | ( 1 << 8)) << 32),
	PC3_TIM1_CH4             = (pinconf_t)PC3   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC3_SAI1_D1              = (pinconf_t)PC3   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PC3_TIM1_BKIN2           = (pinconf_t)PC3   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC3_QUADSPI1_BK2_IO2     = (pinconf_t)PC3   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PC3_SAI1_SD_A            = (pinconf_t)PC3   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32),
	PC3_EVENTOUT             = (pinconf_t)PC3   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC4_TIM1_ETR             = (pinconf_t)PC4   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC4_I2C2_SCL             = (pinconf_t)PC4   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC4_USART1_TX            = (pinconf_t)PC4   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PC4_QUADSPI1_BK2_IO3     = (pinconf_t)PC4   | ((pinconf_t)(GPIO_AFOUT | (10 << 8)) << 32), // Cat3,4 only
	PC4_EVENTOUT             = (pinconf_t)PC4   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC5_TIM15_BKIN           = (pinconf_t)PC5   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC5_SAI1_D3              = (pinconf_t)PC5   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32),
	PC5_TIM1_CH4N            = (pinconf_t)PC5   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC5_USART1_RX            = (pinconf_t)PC5   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32),
	PC5_HRTIM1_EEV10         = (pinconf_t)PC5   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PC5_EVENTOUT             = (pinconf_t)PC5   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC6_TIM3_CH1             = (pinconf_t)PC6   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC6_HRTIM1_EEV10         = (pinconf_t)PC6   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat4 only
	PC6_TIM8_CH1             = (pinconf_t)PC6   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC6_I2S2_MCK             = (pinconf_t)PC6   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC6_COMP6_OUT            = (pinconf_t)PC6   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32), // Cat3,4 only
	PC6_I2C4_SCL             = (pinconf_t)PC6   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32), // Cat3,4 only
	PC6_HRTIM1_CHF1          = (pinconf_t)PC6   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PC6_EVENTOUT             = (pinconf_t)PC6   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC7_TIM3_CH2             = (pinconf_t)PC7   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC7_HRTIM1_FLT5          = (pinconf_t)PC7   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat4 only
	PC7_TIM8_CH2             = (pinconf_t)PC7   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC7_I2S3_MCK             = (pinconf_t)PC7   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC7_COMP5_OUT            = (pinconf_t)PC7   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32), // Cat3,4 only
	PC7_I2C4_SDA             = (pinconf_t)PC7   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32), // Cat3,4 only
	PC7_HRTIM1_CHF2          = (pinconf_t)PC7   | ((pinconf_t)(GPIO_AFOUT | (13 << 8)) << 32), // Cat4 only
	PC7_EVENTOUT             = (pinconf_t)PC7   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC8_TIM3_CH3             = (pinconf_t)PC8   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC8_HRTIM1_CHE1          = (pinconf_t)PC8   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat4 only
	PC8_TIM8_CH3             = (pinconf_t)PC8   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC8_TIM20_CH3            = (pinconf_t)PC8   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32), // Cat3,4 only
	PC8_COMP7_OUT            = (pinconf_t)PC8   | ((pinconf_t)(GPIO_AFOUT | ( 7 << 8)) << 32), // Cat3,4 only
	PC8_I2C3_SCL             = (pinconf_t)PC8   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PC8_EVENTOUT             = (pinconf_t)PC8   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PC9_TIM3_CH4             = (pinconf_t)PC9   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PC9_HRTIM1_CHE2          = (pinconf_t)PC9   | ((pinconf_t)(GPIO_AFOUT | ( 3 << 8)) << 32), // Cat4 only
	PC9_TIM8_CH4             = (pinconf_t)PC9   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PC9_I2SCKIN              = (pinconf_t)PC9   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32),
	PC9_TIM8_BKIN2           = (pinconf_t)PC9   | ((pinconf_t)(GPIO_AFOUT | ( 6 << 8)) << 32),
	PC9_I2C3_SDA             = (pinconf_t)PC9   | ((pinconf_t)(GPIO_AFOUT | ( 8 << 8)) << 32),
	PC9_EVENTOUT             = (pinconf_t)PC9   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
	PD2_TIM3_ETR             = (pinconf_t)PD2   | ((pinconf_t)(GPIO_AFOUT | ( 2 << 8)) << 32),
	PD2_TIM8_BKIN            = (pinconf_t)PD2   | ((pinconf_t)(GPIO_AFOUT | ( 4 << 8)) << 32),
	PD2_UART5_RX             = (pinconf_t)PD2   | ((pinconf_t)(GPIO_AFOUT | ( 5 << 8)) << 32), // Cat3,4 only
	PD2_EVENTOUT             = (pinconf_t)PD2   | ((pinconf_t)(GPIO_AFOUT | (15 << 8)) << 32),
};

static inline enum GPIO_Pin pinfor(enum GPIO_Mux m) { return (enum GPIO_Pin)(uint32_t)m; }
